name: Docker CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: create apikey
        env:
          APIKEY: ${{secrets.APIKEY}}
        run: |
          cd nush-llm-chatbot/llamaindex
          touch apikey
          echo "$APIKEY" >> apikey
      - name: Push image to AppVenture registry
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          registry: registry.nush.app
          repository: nush-llm-chatbot
          tags: latest